### PR TITLE
2.0.0 rc1

### PR DESCRIPTION
**Pull request by 84564221**
An updated version for [dekujs/deku](https://github.com/dekujs/deku) v2 API.

### CODE REVIEW

**Comment by 84564221** [comment]
`magic-virtual-element` depends on [deku](https://github.com/dekujs/deku) in my PR, since [virtual-element](https://github.com/dekujs/virtual-element) has been replaced by `element.create()` in v2 (deprecated).

**Comment by anthonyshort** [comment]
Woah nice work. The dependency should be ok for now.

**Comment by kevva** [comment]
Could you do a release?

**Comment by kevva** [comment]
Could you do a release?

**Comment by anthonyshort** [comment]
Done!

**Pull request merged**
